---
- block:  
  - name: Reload ElasticSearch Service
    systemd:
      daemon_reload: yes

  - name: Start ElasticSearch Service
    service:
      name: elasticsearch
      enabled: yes
      state: started
  serial: 1
