---
- name: Create ElasticSearch Self-Signed Certificates Directory
  file:
    path: /etc/elasticsearch/certs
    owner: root
    group: elasticsearch
    mode: u=rwx,g=rs,o=rx
    state: directory

- name: Generate ElasticSearch Self-Signed CA Certificate in First Master
  command: /usr/share/elasticsearch/bin/elasticsearch-certutil ca --pass '' --out /etc/elasticsearch/certs/elastic-stack-ca.p12
  run_once: true
  when:
    - inventory_hostname == groups.masters[0]

- name: Set ElasticSearch Self-Signed CA Certificate Ownership in First Master
  file:
    path: /etc/elasticsearch/certs/elastic-stack-ca.p12
    owner: root
    group: elasticsearch
    mode: 0660
    state: file
  run_once: true
  when:
    - inventory_hostname == groups.masters[0]

- name: Generate ElasticSearch Self-Signed Certificate in First Master
  command: /usr/share/elasticsearch/bin/elasticsearch-certutil cert --ca-pass '' --ca /etc/elasticsearch/certs/elastic-stack-ca.p12 --pass '' --out /etc/elasticsearch/certs/elastic-certificates.p12
  run_once: true
  when:
    - inventory_hostname == groups.masters[0]

- name: Set ElasticSearch Self-Signed Certificate Ownership in First Master
  file:
    path: /etc/elasticsearch/certs/elastic-certificates.p12
    owner: root
    group: elasticsearch
    mode: 0660
    state: file
  run_once: true
  when:
    - inventory_hostname == groups.masters[0]

- name: Copy ElasticSearch Self-Signed Certificates Directory from First Master
  synchronize:
    src: /etc/elasticsearch/certs
    dest: /etc/elasticsearch/certs
    checksum: yes
    mode: pull
  delegate_to: groups.masters[0]
  when:
    - inventory_hostname != groups.masters[0]
