---
- name: Setup ElasticSearch Bootstrap Password
  shell: echo '{{ elasticsearch_password }}' | /usr/share/elasticsearch/bin/elasticsearch-keystore add -x 'bootstrap.password'

- name: Reload ElasticSearch Service
  systemd:
    daemon_reload: yes

- name: Stop ElasticSearch Service
  service:
    name: elasticsearch
    enabled: yes
    state: restrated
