---
- name: Create ElasticSearch Self-Signed Certificates Directory
  file:
    path: /etc/elasticsearch/certs
    owner: root
    group: elasticsearch
    mode: 0755
    state: directory

- name: Remove ElasticSearch Self-Signed Certificates File if Already Exist
  file:
    path: "{{ item }}"
    state: absent
  with_items:
   - /etc/elasticsearch/certs/elastic-stack-ca.p12
   - /etc/elasticsearch/certs/elastic-certificates.p12
   
- name: Generate ElasticSearch Self-Signed CA Certificate in First Master
  command: /usr/share/elasticsearch/bin/elasticsearch-certutil ca --pass '' --out /etc/elasticsearch/certs/elastic-stack-ca.p12
  run_once: true
  when:
    - inventory_hostname == groups.masters[0]

- name: Generate ElasticSearch Self-Signed Certificate in First Master
  command: /usr/share/elasticsearch/bin/elasticsearch-certutil cert --ca-pass '' --ca /etc/elasticsearch/certs/elastic-stack-ca.p12 --pass '' --out /etc/elasticsearch/certs/elastic-certificates.p12
  run_once: true
  when:
    - inventory_hostname == groups.masters[0]

- name: Copy ElasticSearch Self-Signed Certificates Directory from First Master
  synchronize:
    src: /etc/elasticsearch/certs
    dest: /tmp
    ssh_args: "-l {{ ansible_user }}"
    set_remote_user: no
    checksum: yes
    mode: pull
  delegate_to: localhost
  run_once: true
  when:
    - inventory_hostname == groups.masters[0]

- name: Distribute ElasticSearch Self-Signed Certificates Directory from First Master
  synchronize:
    src: /tmp/certs
    dest: /etc/elasticsearch
    ssh_args: "-l {{ ansible_user }}"
    set_remote_user: no
    checksum: yes
    mode: push
  delegate_to: localhost
  when:
    - inventory_hostname != groups.masters[0]

- name: Remove Temporary ElasticSearch Self-Signed Certificates Directory
  file:
    path: "{{ item }}"
    state: absent
  delegate_to: localhost
  run_once: true
  with_items:
    - /tmp/certs/elastic-stack-ca.p12
    - /tmp/certs/elastic-certificates.p12
    - /tmp/certs

- name: Set ElasticSearch Self-Signed Certificate Ownership
  file:
    path: "{{ item }}"
    owner: root
    group: elasticsearch
    mode: 0660
    state: file
  with_items:
   - /etc/elasticsearch/certs/elastic-stack-ca.p12
   - /etc/elasticsearch/certs/elastic-certificates.p12