---
- name: Create ElasticSearch Data Directory
  file:
    path: "{{ item }}"
    state: directory
    owner: elasticsearch
    group: elasticsearch
    mode: u=rwx,g=rs,o-rwx
    recurse: true
  with_items:
    - /var/lib/elasticsearch
    - /var/lib/elasticsearch/data
    - /var/lib/elasticsearch/logs

- name: Create ElasticSearch Log Directory
  file:
    src: /var/lib/elasticsearch/logs
    dest: /var/log/elasticsearch
    owner: elasticsearch
    group: elasticsearch
    state: link
