---
- name: Reload ElasticSearch Service
  throttle: 1
  systemd:
    daemon_reload: yes

- name: Start ElasticSearch Service
  throttle: 1
  service:
    name: elasticsearch
    enabled: yes
    state: started
